on:
  push:
    tags:
      - "*"


  workflow_dispatch:
  # please work. 
jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: Deploy to Nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: 'fourrie.net'
          nekoweb-username: 'chicorbeep'
          directory: 'public'
