

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    if: ${{ github.ref == 'refs/tags/main' }}



    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: 'c74e.fyi'
          nekoweb-username: 'chicorbeep'
          directory: 'public'

